#!/usr/bin/env perl

# Description: Nagios check to get MHA status

use strict;
use warnings FATAL => 'all';

use Getopt::Long qw(:config pass_through);
use Pod::Usage;
use MHA::ManagerConst;
use MHA::ManagerAdminWrapper;

my $rc = 0;
eval { $rc = MHA::ManagerAdminWrapper::check_status(@ARGV); };
if ($@) {
  $rc = 1;
}
exit $rc;
